// <auto-generated />
using System;
using AstroDesk.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AstroDesk.Data.Migrations
{
    [DbContext(typeof(AstroDeskDbContext))]
    [Migration("20260716100509_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.29");

            modelBuilder.Entity("AstroDesk.Core.Entities.AppSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("UpdatedAt");

                    b.ToTable("AppSettings", null, t =>
                        {
                            t.HasCheckConstraint("CK_AppSetting_UpdatedAt", "\"UpdatedAt\" >= \"CreatedAt\"");

                            t.HasCheckConstraint("CK_AppSettings_Key_NotBlank", "length(trim(\"Key\")) > 0");

                            t.HasCheckConstraint("CK_AppSettings_ValueType_NotBlank", "length(trim(\"ValueType\")) > 0");
                        });
                });

            modelBuilder.Entity("AstroDesk.Core.Entities.EquipmentProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Accessories")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Camera")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lens")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("Tripod")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsDefault")
                        .IsUnique()
                        .HasFilter("\"IsDefault\" = 1");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("UpdatedAt");

                    b.ToTable("EquipmentProfiles", null, t =>
                        {
                            t.HasCheckConstraint("CK_EquipmentProfile_UpdatedAt", "\"UpdatedAt\" >= \"CreatedAt\"");

                            t.HasCheckConstraint("CK_EquipmentProfiles_Camera_NotBlank", "length(trim(\"Camera\")) > 0");

                            t.HasCheckConstraint("CK_EquipmentProfiles_Lens_NotBlank", "length(trim(\"Lens\")) > 0");

                            t.HasCheckConstraint("CK_EquipmentProfiles_Name_NotBlank", "length(trim(\"Name\")) > 0");
                        });
                });

            modelBuilder.Entity("AstroDesk.Core.Entities.OverlayPreset", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<double>("LineThickness")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<double>("Opacity")
                        .HasColumnType("REAL");

                    b.Property<bool>("ShowCenterCrosshair")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowCircle")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowCustomRectangle")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowDiagonalGuides")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowHorizon")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowRuleOfThirds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowSafeArea")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsDefault")
                        .IsUnique()
                        .HasFilter("\"IsDefault\" = 1");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("UpdatedAt");

                    b.ToTable("OverlayPresets", null, t =>
                        {
                            t.HasCheckConstraint("CK_OverlayPreset_UpdatedAt", "\"UpdatedAt\" >= \"CreatedAt\"");

                            t.HasCheckConstraint("CK_OverlayPresets_ColorHex", "(length(\"ColorHex\") = 7 AND \"ColorHex\" GLOB '#[0-9A-F][0-9A-F][0-9A-F][0-9A-F][0-9A-F][0-9A-F]') OR (length(\"ColorHex\") = 9 AND \"ColorHex\" GLOB '#[0-9A-F][0-9A-F][0-9A-F][0-9A-F][0-9A-F][0-9A-F][0-9A-F][0-9A-F]')");

                            t.HasCheckConstraint("CK_OverlayPresets_LineThickness", "\"LineThickness\" > 0.0 AND \"LineThickness\" <= 20.0");

                            t.HasCheckConstraint("CK_OverlayPresets_Name_NotBlank", "length(trim(\"Name\")) > 0");

                            t.HasCheckConstraint("CK_OverlayPresets_Opacity", "\"Opacity\" >= 0.0 AND \"Opacity\" <= 1.0");
                        });
                });

            modelBuilder.Entity("AstroDesk.Core.Entities.SavedLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("ElevationMeters")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("TimeZoneId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsDefault")
                        .IsUnique()
                        .HasFilter("\"IsDefault\" = 1");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("UpdatedAt");

                    b.ToTable("SavedLocations", null, t =>
                        {
                            t.HasCheckConstraint("CK_SavedLocation_UpdatedAt", "\"UpdatedAt\" >= \"CreatedAt\"");

                            t.HasCheckConstraint("CK_SavedLocations_Latitude", "\"Latitude\" >= -90.0 AND \"Latitude\" <= 90.0");

                            t.HasCheckConstraint("CK_SavedLocations_Longitude", "\"Longitude\" >= -180.0 AND \"Longitude\" <= 180.0");

                            t.HasCheckConstraint("CK_SavedLocations_Name_NotBlank", "length(trim(\"Name\")) > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("1eb6fb77-e935-4f2f-b635-c18474befb25"),
                            CreatedAt = 639197568000000000L,
                            ElevationMeters = 0.0,
                            IsDefault = false,
                            Latitude = 33.893799999999999,
                            Longitude = 35.501800000000003,
                            Name = "Beirut",
                            TimeZoneId = "Asia/Beirut",
                            UpdatedAt = 639197568000000000L
                        },
                        new
                        {
                            Id = new Guid("ad8f2bee-f3fd-4f2c-ab40-416ff6df6738"),
                            CreatedAt = 639197568000000000L,
                            ElevationMeters = 900.0,
                            IsDefault = false,
                            Latitude = 33.846299999999999,
                            Longitude = 35.902000000000001,
                            Name = "Zahle",
                            TimeZoneId = "Asia/Beirut",
                            UpdatedAt = 639197568000000000L
                        },
                        new
                        {
                            Id = new Guid("3685a745-3e51-4824-bf11-ed51e6581b84"),
                            CreatedAt = 639197568000000000L,
                            ElevationMeters = 1850.0,
                            IsDefault = true,
                            Latitude = 34.011099999999999,
                            Longitude = 35.828499999999998,
                            Name = "Faraya",
                            TimeZoneId = "Asia/Beirut",
                            UpdatedAt = 639197568000000000L
                        },
                        new
                        {
                            Id = new Guid("177ce03d-d347-4471-aa63-ad942906396d"),
                            CreatedAt = 639197568000000000L,
                            ElevationMeters = 1450.0,
                            IsDefault = false,
                            Latitude = 34.209000000000003,
                            Longitude = 35.920000000000002,
                            Name = "Tannourine",
                            TimeZoneId = "Asia/Beirut",
                            UpdatedAt = 639197568000000000L
                        },
                        new
                        {
                            Id = new Guid("499b960b-71bb-4393-82bb-d71e68958a22"),
                            CreatedAt = 639197568000000000L,
                            ElevationMeters = 950.0,
                            IsDefault = false,
                            Latitude = 33.541699999999999,
                            Longitude = 35.584400000000002,
                            Name = "Jezzine",
                            TimeZoneId = "Asia/Beirut",
                            UpdatedAt = 639197568000000000L
                        },
                        new
                        {
                            Id = new Guid("da59de93-b9da-451a-a784-0508817005fc"),
                            CreatedAt = 639197568000000000L,
                            ElevationMeters = 900.0,
                            IsDefault = false,
                            Latitude = 33.850000000000001,
                            Longitude = 35.899999999999999,
                            Name = "Bekaa Valley",
                            TimeZoneId = "Asia/Beirut",
                            UpdatedAt = 639197568000000000L
                        });
                });

            modelBuilder.Entity("AstroDesk.Core.Entities.SessionAstronomySnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CapturedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DarkSkyWindowEnd")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DarkSkyWindowStart")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("EndOfAstronomicalTwilight")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("MoonAltitudeDegrees")
                        .HasColumnType("REAL");

                    b.Property<double?>("MoonIlluminationPercent")
                        .HasColumnType("REAL");

                    b.Property<string>("MoonPhase")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long?>("Moonrise")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("Moonset")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProviderName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ShootingSessionId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("StartOfAstronomicalTwilight")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("Sunrise")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("Sunset")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CapturedAt");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ShootingSessionId")
                        .IsUnique();

                    b.HasIndex("UpdatedAt");

                    b.ToTable("SessionAstronomySnapshots", null, t =>
                        {
                            t.HasCheckConstraint("CK_SessionAstronomySnapshot_UpdatedAt", "\"UpdatedAt\" >= \"CreatedAt\"");

                            t.HasCheckConstraint("CK_SessionAstronomySnapshots_DarkSkyWindow", "\"DarkSkyWindowStart\" IS NULL OR \"DarkSkyWindowEnd\" IS NULL OR \"DarkSkyWindowEnd\" >= \"DarkSkyWindowStart\"");

                            t.HasCheckConstraint("CK_SessionAstronomySnapshots_MoonAltitude", "\"MoonAltitudeDegrees\" IS NULL OR (\"MoonAltitudeDegrees\" >= -90.0 AND \"MoonAltitudeDegrees\" <= 90.0)");

                            t.HasCheckConstraint("CK_SessionAstronomySnapshots_MoonIllumination", "\"MoonIlluminationPercent\" IS NULL OR (\"MoonIlluminationPercent\" >= 0.0 AND \"MoonIlluminationPercent\" <= 100.0)");
                        });
                });

            modelBuilder.Entity("AstroDesk.Core.Entities.SessionNote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<long>("NotedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ShootingSessionId")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("NotedAt");

                    b.HasIndex("ShootingSessionId");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("ShootingSessionId", "NotedAt");

                    b.ToTable("SessionNotes", null, t =>
                        {
                            t.HasCheckConstraint("CK_SessionNote_UpdatedAt", "\"UpdatedAt\" >= \"CreatedAt\"");

                            t.HasCheckConstraint("CK_SessionNotes_Content_NotBlank", "length(trim(\"Content\")) > 0");

                            t.HasCheckConstraint("CK_SessionNotes_Kind", "\"Kind\" IN ('General','Observation','Problem')");
                        });
                });

            modelBuilder.Entity("AstroDesk.Core.Entities.SessionScreenshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CapturedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageFormat")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IncludesOverlays")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ShootingSessionId")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CapturedAt");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ShootingSessionId");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("ShootingSessionId", "FilePath")
                        .IsUnique();

                    b.ToTable("SessionScreenshots", null, t =>
                        {
                            t.HasCheckConstraint("CK_SessionScreenshot_UpdatedAt", "\"UpdatedAt\" >= \"CreatedAt\"");

                            t.HasCheckConstraint("CK_SessionScreenshots_FilePath_NotBlank", "length(trim(\"FilePath\")) > 0");

                            t.HasCheckConstraint("CK_SessionScreenshots_ImageFormat_NotBlank", "length(trim(\"ImageFormat\")) > 0");
                        });
                });

            modelBuilder.Entity("AstroDesk.Core.Entities.SessionWeatherSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CapturedAt")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("CloudCoverPercent")
                        .HasColumnType("REAL");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("DewPointCelsius")
                        .HasColumnType("REAL");

                    b.Property<string>("DewRisk")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<double?>("HumidityPercent")
                        .HasColumnType("REAL");

                    b.Property<string>("ProviderName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ShootingSessionId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("TemperatureCelsius")
                        .HasColumnType("REAL");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("VisibilityKilometers")
                        .HasColumnType("REAL");

                    b.Property<double?>("WindSpeedKilometersPerHour")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("CapturedAt");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ShootingSessionId")
                        .IsUnique();

                    b.HasIndex("UpdatedAt");

                    b.ToTable("SessionWeatherSnapshots", null, t =>
                        {
                            t.HasCheckConstraint("CK_SessionWeatherSnapshot_UpdatedAt", "\"UpdatedAt\" >= \"CreatedAt\"");

                            t.HasCheckConstraint("CK_SessionWeatherSnapshots_CloudCover", "\"CloudCoverPercent\" IS NULL OR (\"CloudCoverPercent\" >= 0.0 AND \"CloudCoverPercent\" <= 100.0)");

                            t.HasCheckConstraint("CK_SessionWeatherSnapshots_DewRisk", "\"DewRisk\" IN ('Unavailable','Low','Moderate','High')");

                            t.HasCheckConstraint("CK_SessionWeatherSnapshots_Humidity", "\"HumidityPercent\" IS NULL OR (\"HumidityPercent\" >= 0.0 AND \"HumidityPercent\" <= 100.0)");

                            t.HasCheckConstraint("CK_SessionWeatherSnapshots_Visibility", "\"VisibilityKilometers\" IS NULL OR \"VisibilityKilometers\" >= 0.0");

                            t.HasCheckConstraint("CK_SessionWeatherSnapshots_WindSpeed", "\"WindSpeedKilometersPerHour\" IS NULL OR \"WindSpeedKilometersPerHour\" >= 0.0");
                        });
                });

            modelBuilder.Entity("AstroDesk.Core.Entities.ShootingSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int?>("BatteryPercentageAtEnd")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BatteryPercentageAtStart")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Camera")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CurrentSessionSlot")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("INTEGER")
                        .HasComputedColumnSql("CASE WHEN \"Status\" IN ('Active','Paused') THEN 1 ELSE NULL END", true);

                    b.Property<long>("DelayBetweenFrames")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("EndTime")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("EquipmentProfileId")
                        .HasColumnType("TEXT");

                    b.Property<long>("ExposureTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FocusSetting")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("FrameCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("InitialDelay")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Iso")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<long?>("PausedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlannedFrameCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Problems")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RawEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SelectedPhoneLens")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<long?>("StartTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<long?>("StorageBytesAtEnd")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("StorageBytesAtStart")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<long>("TotalPausedDuration")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WhiteBalance")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CurrentSessionSlot")
                        .IsUnique()
                        .HasFilter("\"CurrentSessionSlot\" IS NOT NULL");

                    b.HasIndex("EndTime");

                    b.HasIndex("EquipmentProfileId");

                    b.HasIndex("LocationName");

                    b.HasIndex("Rating");

                    b.HasIndex("SessionType");

                    b.HasIndex("StartTime");

                    b.HasIndex("TargetName");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("Status", "StartTime");

                    b.ToTable("ShootingSessions", null, t =>
                        {
                            t.HasCheckConstraint("CK_ShootingSession_UpdatedAt", "\"UpdatedAt\" >= \"CreatedAt\"");

                            t.HasCheckConstraint("CK_ShootingSessions_Battery", "(\"BatteryPercentageAtStart\" IS NULL OR (\"BatteryPercentageAtStart\" >= 0 AND \"BatteryPercentageAtStart\" <= 100)) AND (\"BatteryPercentageAtEnd\" IS NULL OR (\"BatteryPercentageAtEnd\" >= 0 AND \"BatteryPercentageAtEnd\" <= 100))");

                            t.HasCheckConstraint("CK_ShootingSessions_Delays", "\"DelayBetweenFrames\" >= 0 AND \"InitialDelay\" >= 0");

                            t.HasCheckConstraint("CK_ShootingSessions_ExposureTime", "\"ExposureTime\" > 0");

                            t.HasCheckConstraint("CK_ShootingSessions_FrameCounts", "\"FrameCount\" >= 0 AND \"PlannedFrameCount\" >= 0");

                            t.HasCheckConstraint("CK_ShootingSessions_Iso", "\"Iso\" IS NULL OR \"Iso\" > 0");

                            t.HasCheckConstraint("CK_ShootingSessions_Latitude", "\"Latitude\" >= -90.0 AND \"Latitude\" <= 90.0");

                            t.HasCheckConstraint("CK_ShootingSessions_LocationName_NotBlank", "length(trim(\"LocationName\")) > 0");

                            t.HasCheckConstraint("CK_ShootingSessions_Longitude", "\"Longitude\" >= -180.0 AND \"Longitude\" <= 180.0");

                            t.HasCheckConstraint("CK_ShootingSessions_Rating", "\"Rating\" IS NULL OR (\"Rating\" >= 1 AND \"Rating\" <= 5)");

                            t.HasCheckConstraint("CK_ShootingSessions_SessionType", "\"SessionType\" IN ('MilkyWay','Starscape','StarTrails','Moon','Planet','Constellation','DeepSky','Timelapse','TestSession','Other')");

                            t.HasCheckConstraint("CK_ShootingSessions_Status", "\"Status\" IN ('Planned','Active','Paused','Completed')");

                            t.HasCheckConstraint("CK_ShootingSessions_StatusTimeline", "(\"Status\" = 'Planned' AND \"StartTime\" IS NULL AND \"EndTime\" IS NULL AND \"PausedAt\" IS NULL) OR (\"Status\" = 'Active' AND \"StartTime\" IS NOT NULL AND \"EndTime\" IS NULL AND \"PausedAt\" IS NULL) OR (\"Status\" = 'Paused' AND \"StartTime\" IS NOT NULL AND \"EndTime\" IS NULL AND \"PausedAt\" IS NOT NULL) OR (\"Status\" = 'Completed' AND \"StartTime\" IS NOT NULL AND \"EndTime\" IS NOT NULL AND \"PausedAt\" IS NULL)");

                            t.HasCheckConstraint("CK_ShootingSessions_Storage", "(\"StorageBytesAtStart\" IS NULL OR \"StorageBytesAtStart\" >= 0) AND (\"StorageBytesAtEnd\" IS NULL OR \"StorageBytesAtEnd\" >= 0)");

                            t.HasCheckConstraint("CK_ShootingSessions_TargetName_NotBlank", "length(trim(\"TargetName\")) > 0");

                            t.HasCheckConstraint("CK_ShootingSessions_Timeline", "(\"StartTime\" IS NULL OR \"StartTime\" >= \"CreatedAt\") AND (\"EndTime\" IS NULL OR (\"StartTime\" IS NOT NULL AND \"EndTime\" >= \"StartTime\")) AND (\"PausedAt\" IS NULL OR (\"StartTime\" IS NOT NULL AND \"PausedAt\" >= \"StartTime\"))");

                            t.HasCheckConstraint("CK_ShootingSessions_TotalPausedDuration", "\"TotalPausedDuration\" >= 0");
                        });
                });

            modelBuilder.Entity("AstroDesk.Core.Entities.SessionAstronomySnapshot", b =>
                {
                    b.HasOne("AstroDesk.Core.Entities.ShootingSession", "ShootingSession")
                        .WithOne("AstronomySnapshot")
                        .HasForeignKey("AstroDesk.Core.Entities.SessionAstronomySnapshot", "ShootingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShootingSession");
                });

            modelBuilder.Entity("AstroDesk.Core.Entities.SessionNote", b =>
                {
                    b.HasOne("AstroDesk.Core.Entities.ShootingSession", "ShootingSession")
                        .WithMany("Notes")
                        .HasForeignKey("ShootingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShootingSession");
                });

            modelBuilder.Entity("AstroDesk.Core.Entities.SessionScreenshot", b =>
                {
                    b.HasOne("AstroDesk.Core.Entities.ShootingSession", "ShootingSession")
                        .WithMany("Screenshots")
                        .HasForeignKey("ShootingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShootingSession");
                });

            modelBuilder.Entity("AstroDesk.Core.Entities.SessionWeatherSnapshot", b =>
                {
                    b.HasOne("AstroDesk.Core.Entities.ShootingSession", "ShootingSession")
                        .WithOne("WeatherSnapshot")
                        .HasForeignKey("AstroDesk.Core.Entities.SessionWeatherSnapshot", "ShootingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShootingSession");
                });

            modelBuilder.Entity("AstroDesk.Core.Entities.ShootingSession", b =>
                {
                    b.HasOne("AstroDesk.Core.Entities.EquipmentProfile", "EquipmentProfile")
                        .WithMany("Sessions")
                        .HasForeignKey("EquipmentProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("EquipmentProfile");
                });

            modelBuilder.Entity("AstroDesk.Core.Entities.EquipmentProfile", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("AstroDesk.Core.Entities.ShootingSession", b =>
                {
                    b.Navigation("AstronomySnapshot");

                    b.Navigation("Notes");

                    b.Navigation("Screenshots");

                    b.Navigation("WeatherSnapshot");
                });
#pragma warning restore 612, 618
        }
    }
}
